<?php include __DIR__ . '/../header.html'; ?>

<a href="/posts/create">Criar novo post</a>
<br />
<table>
    <thead>
    <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Content</th>
        <th>Ações</th>
    </tr>
    </thead>
    <tbody>
        <?php foreach ($posts as $post) : ?>
            <tr>
                <td><?php echo $post->getId(); ?></td>
                <td><?php echo $post->getTitle(); ?></td>
                <td><?php echo $post->getContent(); ?></td>
                <td>
                    <a href="/posts/<?php echo $post->getId(); ?>/edit">Editar</a>&nbsp;|&nbsp;
                    <a href="/posts/<?php echo $post->getId(); ?>/remove">Remover</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?php include __DIR__ . '/../header.html';