<div class="row">
    <div class="col-sm-6 col-md-12 col-xs-12 col-left">
        <div aria-live="polite" role="status" id="table-1_info" class="dataTables_info">
            <?php echo sprintf($this->translate('Page %s of %s. Showing from %s to %s of %s entries.'), $this->current, $this->pageCount, $this->firstItemNumber, $this->lastItemNumber, $this->totalItemCount); ?>
        </div>
    </div>
    <div class="col-sm-6 col-md-12 col-xs-12 col-right">
        <div id="table-1_paginate" class="dataTables_paginate paging_bootstrap">

            <?php if ($this->pageCount): ?>

            <ul class="pagination">

                <!-- First page link -->
                <?php if (isset($this->previous)): ?>
                    <li>
                        <?php
                        $params = array('page' => $this->first);
                        ?>
                        <a href="<?php echo $this->url($this->route, $params); ?>"
                           title="<?php echo $this->translate('First page'); ?>">
                            <i class="entypo-left-thin"></i>&nbsp;<?php echo $this->translate('First page'); ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="disabled"><a href="#" title="<?php echo $this->translate('First page'); ?>">
                            <i class="entypo-left-thin"></i>&nbsp;<?php echo $this->translate('First page'); ?>
                        </a>
                    </li>
                <?php endif; ?>

                <!-- Previous page link -->
                <?php if (isset($this->previous)): ?>
                    <li>
                        <?php
                        $params = array('page' => $this->previous);
                        ?>
                        <a href="<?php echo $this->url($this->route, $params); ?>">
                            <i class="entypo-left-open-mini"></i>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="disabled"><a href="#"><i class="entypo-left-open-mini"></i></a></li>
                <?php endif; ?>

                <!-- Numbered page links -->
                <?php foreach ($this->pagesInRange as $page): ?>
                    <?php if ($page != $this->current): ?>
                        <li>
                            <?php
                            $pagesParams = array('page' => $page);
                            ?>
                            <a href="<?php echo $this->url($this->route, $pagesParams); ?>">
                                <?php echo $page; ?>
                            </a>
                        </li>
                    <?php else: ?>
                        <li class="active"><a href="#"><?php echo $page; ?></a></li>
                    <?php endif; ?>
                <?php endforeach; ?>

                <!-- Next page link -->
                <?php if (isset($this->next)): ?>
                    <li>
                        <?php
                        $nextParams = array('page' => $this->next);
                        ?>
                        <a href="<?php echo $this->url($this->route, $nextParams); ?>">
                            <i class="entypo-right-open-mini"></i>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="disabled"><a href="#"><i class="entypo-right-open-mini"></i></a></li>
                <?php endif; ?>

                <?php endif; ?>

                <!-- Last page link -->
                <?php if (isset($this->next)): ?>
                    <li>
                        <?php
                        $lastParams = array('page' => $this->last);
                        ?>
                        <a href="<?php echo $this->url($this->route, $lastParams); ?>"
                           title="<?php echo $this->translate('Last page'); ?>">
                            <?php echo $this->translate('Last page'); ?>&nbsp;>></i>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="disabled"><a href="#" title="<?php echo $this->translate('Last page'); ?>">
                            <?php echo $this->translate('Last page'); ?>&nbsp;<i class="entypo-right-thin"></i>
                        </a>
                    </li>
                <?php endif; ?>

            </ul>
        </div>

    </div>
</div>